query GET_TASKS_BY_USER($userId: ID!, $page: Int) {
    tasksByUser(
        user_id: $userId
        orderBy: [
            { field: IS_COMPLETED, order: ASC }
            { field: UPDATED_AT, order: DESC }
        ]
        page: $page
    ) {
        data {
            id
            description
            order {
                id
                video {
                    id
                    name
                }
            }
            user_id
            is_completed
            created_at
            updated_at
        }
        paginatorInfo {
            currentPage
            lastPage
            hasMorePages
        }
    }
}
